language: java

branches:
  except:
    - tmp

jdk:
  - openjdk8
  - oraclejdk8

script:
  - ./gradlew check assembleJavadoc

stages:
  - test
  - mutation-test

jobs:
  include:
    - stage: mutation-test
      jdk: oraclejdk8
      script: ./gradlew pitest coveralls
