language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: ./gradlew build --exclude-task signArchives
after_success:
  - ./gradlew coveralls

addons:
  hosts:
    - travis-issue-5227-workaround
  hostname: travis-issue-5227-workaround
