server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: keystore.jks
      keyStorePassword: p@ssw0rd
      validateCerts: false
  adminConnectors:
      - type: http
        port: 8081  
