server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: keystore.jks
      keyStorePassword: p@ssw0rd
      validateCerts: false
  adminConnectors:
      - type: http
        port: 8081
  rootPath: '/api/'
  requestLog:
    appenders: []

logging:
  level: INFO
  loggers:
    javax.ws.rs.ext.MessageBodyWriter: DEBUG
  appenders:
    - type: console
